{
 "title": "AWS ALB",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "load_balancer", "query": { "query": "label_values(load_balancer)" } },
   { "name": "target_group", "query": { "query": "label_values(target_group)" } },
   {
    "name": "availability_zone",
    "query": {
     "query": "label_values(availability_zone)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_sum{load_balancer=\"$load_balancer\", target_group=\"\", availability_zone=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per AZ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_sum{load_balancer=\"$load_balancer\", target_group=\"\", availability_zone=~\"$availability_zone\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "200's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_2_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "300's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_3_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "400's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_4_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_5_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "LB 500's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "502 Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_elb_502_count_sum{load_balancer=\"$load_balancer\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "503 Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_elb_503_count_sum{load_balancer=\"$load_balancer\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "504 Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_elb_504_count_sum{load_balancer=\"$load_balancer\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Target Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_request_count_sum{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "avg by (availability_zone) (aws_applicationelb_target_response_time_average{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg by (availability_zone) (aws_applicationelb_healthy_host_count_average{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Un-Healthy Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "avg by (availability_zone) (aws_applicationelb_un_healthy_host_count_average{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target 2xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_2_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target 3xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_3_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target 4xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_4_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target 5xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum by (availability_zone) (aws_applicationelb_httpcode_target_5_xx_count_sum{load_balancer=\"$load_balancer\", target_group=\"$target_group\", availability_zone=~\"$availability_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}